// Generated by tests/fixtures/generate.py; do not edit.
#pragma once
namespace fixture_manifest {
struct Entry { const wchar_t* path; const char* sha256; unsigned triangles; unsigned points; };
inline constexpr Entry geometry[] = {
    { L"corpus/A-small-glb.glb", "412f9110575c0b425d8cdc4726ca5a59c4e91c09de4f3d56a226fd1f2fbb6240", 240, 0 },
    { L"corpus/A-small-stl.stl", "5c93493ea081b589d57e2c4f12fdb0a01b0f0ba96b430d66d1d234bc254c975f", 240, 0 },
    { L"corpus/A-small-ply-mesh-le.ply", "5afbebf1508a09952a37478c150923c239f8678011107944c5d741918b805243", 240, 0 },
    { L"corpus/A-small-ply-mesh-be.ply", "94750f6c696cbe0e7e233d6d645ee488347b7c7b24ae5c1535dbe2d68dbb3dc5", 240, 0 },
    { L"corpus/A-small-ply-points-le.ply", "a8498cded553d61151db26dd9ba7b4bc6f21f756906b1a330e36780dbc92ace7", 0, 240 },
    { L"corpus/A-small-ply-points-be.ply", "b3513396ab8889eac9d6a6c9b9fc609eeccfe520ecb90c2629ceee1f7cd4d68b", 0, 240 },
};
struct File { const wchar_t* path; const char* sha256; };
inline constexpr File files[] = {
    { L"corpus/A-small-glb.glb", "412f9110575c0b425d8cdc4726ca5a59c4e91c09de4f3d56a226fd1f2fbb6240" },
    { L"corpus/A-small-stl.stl", "5c93493ea081b589d57e2c4f12fdb0a01b0f0ba96b430d66d1d234bc254c975f" },
    { L"corpus/A-small-ply-mesh-le.ply", "5afbebf1508a09952a37478c150923c239f8678011107944c5d741918b805243" },
    { L"corpus/A-small-ply-mesh-be.ply", "94750f6c696cbe0e7e233d6d645ee488347b7c7b24ae5c1535dbe2d68dbb3dc5" },
    { L"corpus/A-small-ply-points-le.ply", "a8498cded553d61151db26dd9ba7b4bc6f21f756906b1a330e36780dbc92ace7" },
    { L"corpus/A-small-ply-points-be.ply", "b3513396ab8889eac9d6a6c9b9fc609eeccfe520ecb90c2629ceee1f7cd4d68b" },
    { L"corpus/Pressure.glb", "412f9110575c0b425d8cdc4726ca5a59c4e91c09de4f3d56a226fd1f2fbb6240" },
    { L"corpus/sidecar-approved.gltf", "7b89b9e341e255c64a2d350a0896ccfd98a804506a4816835928f24c96657227" },
    { L"corpus/sidecar-missing.gltf", "6788ad4477f83612828df03d01d905ef268060be6d4baa5e28a903099e8318a5" },
    { L"corpus/sidecar-traversal.gltf", "4c9c053fa19cd6c71177f5d819895f6d9bbc9a799decdadc2927c691c5dd80c7" },
    { L"corpus/sidecar-encoded-traversal.gltf", "4cbba2d7c0deb03f6360ef4c51a506517385732252fa2fd9e622be14d2dc4e83" },
    { L"corpus/sidecar-absolute.gltf", "dd21d45f117c0ff78352b61a53418cbb7cc58efd1c028f186e263d7c0683f3d6" },
    { L"corpus/sidecar-network.gltf", "a3377e18d94c4c5479c99431db24cb08a8251da6c367a110f5df9d07fa30ffbd" },
    { L"corpus/sidecar-unc.gltf", "cbaf336d741fb505c9a8a9dc071024f3bbca497c7e6de30fa8a2b1ffebd86228" },
    { L"corpus/sidecar-ads.gltf", "1675b70742a0b525b192773b858c94f2db5fb8faecb31d7e28be6e244972954d" },
    { L"corpus/approved.bin", "577f5dd074efad2142c2fd1bc437cdfb72b528f551ef626cfdf45a95c240d241" },
    { L"corpus/sparse-invalid.gltf", "984cae81552ff270d5b039c1d93916bec7b7dcd86d79071b6bc4b91799e9796b" },
    { L"corpus/sparse.bin", "a04e3351807a61b4b5344282fcd688cdc43f8faca65860efdf37127138ebba62" },
    { L"corpus/sparse-valid.gltf", "6406b4d47b5257a6d9a46f230590bfe4b85526435699f5ac6e1e6ff77c981eba" },
    { L"corpus/sparse-valid.bin", "9b963c53b59d395c1c754c12c99ea30362012d987250c3a48d1ab499028cadb9" },
    { L"corpus/Draw-heavy.glb", "569ba584e449e9ed316a7131dfc03177579ecd9ce273410e127ba168246ccfe4" },
    { L"corpus/draco_triangle.glb", "8a72f4877c31738c17f0d8504e7368c4ecd52dae36d30f729c4e79050413f749" },
    { L"corpus/draco_position_only.glb", "9fec2df76ef97746ae0b2503159e9ccde7a8f6a59da85f6bdea1f2fcfda32c45" },
    { L"corpus/basisu_textured_triangle.glb", "fc687c614ce36c140a4037c805b9bb4c95794354235f61ce7e6053300a54b50f" },
    { L"corpus/basisu_corrupt_ktx2.glb", "79bd29527d67669ac79d195d3a09c3bc3a9ae9df6d0b12e7dbfafbb97b892512" },
    { L"corpus/meshopt.glb", "ed4a174748c2a1adaf15b0d8cc28d66e9b4b223495a9c06f19fb175f9501a555" },
    { L"corpus/sample.webp", "86be52bdb7547413cafb3ed175a806a798c65de98b40849e0b974c47d187de65" },
    { L"corpus/webp.gltf", "0e4465f1cb66901ebcd40add49603a0bd273ce7c70378f2b6150589a4d360eb3" },
    { L"corpus/truncated.glb", "c74f919439792582aa4f0b188ec2a928675cdb3ba72797781ceb6dfaa86b313f" },
    { L"corpus/over-limit.stl", "f2394e807625b529c011c4ea437a13f4e774f961c214a26e5e8bcc87bbff09ff" },
    { L"corpus/truncated.stl", "ee76e96d8539348808ead934fbc84c5cdb1475b9396b879af6166bdfc0c4d921" },
    { L"corpus/over-limit.ply", "647cf450e8d67952a773e27b9cb90106ea00b049401390f6baacc84feea7dad1" },
    { L"corpus/empty.ply", "235143d3aac455b75daa35f7bf8688e8b6624c2773113dbb1f89808ad392520e" },
    { L"corpus/manifest.json", "5c0f18b1e19ce6ca5c1f3c3d563ce117ede4b713539132a47ea1b4c445d3b976" },
};
} // namespace fixture_manifest
