// Stage 5 (KTX2/Basis texture transcode) unit tests -- exercise
// import_worker::TranscodeKtx2BasisImage directly against a real
// Basis-Universal-compressed KTX2 file (generated by
// interactive-viewer/tools/gen-test-glbs-ktx2.cpp via the real KTX-Software
// encode API). GltfImportTests.cpp's basisu_textured_triangle.glb/
// basisu_corrupt_ktx2.glb cases separately prove the real end-to-end
// worker path through GltfAdapter.cpp.

#include "TextureTranscodeAdapter.h"

#include "model_core/Ktx2Preflight.h"
#include "model_core/PixelFormats.h"

#include <catch2/catch_test_macros.hpp>
#include <platform/Win32Handle.h>

#include <windows.h>

#include <cstring>
#include <optional>
#include <vector>

#ifndef PREVIEW3D_TEST_ASSETS_DIR
#error "PREVIEW3D_TEST_ASSETS_DIR must be defined by Tests.ImportIsolation.vcxproj"
#endif

namespace {

std::optional<std::vector<std::byte>> ReadFileBytes(const std::wstring& path)
{
    platform::Win32Handle file(CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                                            OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr));
    if (!file) {
        return std::nullopt;
    }
    LARGE_INTEGER size{};
    if (!GetFileSizeEx(file.get(), &size) || size.QuadPart <= 0) {
        return std::nullopt;
    }
    std::vector<std::byte> bytes(static_cast<size_t>(size.QuadPart));
    DWORD bytesRead = 0;
    if (!ReadFile(file.get(), bytes.data(), static_cast<DWORD>(bytes.size()), &bytesRead, nullptr)
        || bytesRead != bytes.size()) {
        return std::nullopt;
    }
    return bytes;
}

// A syntactically valid KTX2 container whose header declares dimensions far
// beyond the product texture cap; the level index is present but the declared
// size is never expanded because the preflight rejects first.
std::vector<std::byte> HostileKtx2Stream(uint32_t width, uint32_t height, uint32_t levels)
{
    std::vector<std::byte> stream(80 + size_t(levels) * 24, std::byte{0});
    const uint8_t magic[12]
        = {0xAB, 0x4B, 0x54, 0x58, 0x20, 0x32, 0x30, 0xBB, 0x0D, 0x0A, 0x1A, 0x0A};
    std::memcpy(stream.data(), magic, sizeof(magic));
    auto put32 = [&stream](size_t offset, uint32_t value) {
        std::memcpy(stream.data() + offset, &value, sizeof(value));
    };
    auto put64 = [&stream](size_t offset, uint64_t value) {
        std::memcpy(stream.data() + offset, &value, sizeof(value));
    };
    put32(12, 0); // vkFormat: Basis
    put32(16, 1); // typeSize
    put32(20, width);
    put32(24, height);
    put32(36, 1); // faceCount
    put32(40, levels);
    for (uint32_t level = 0; level < levels; ++level) {
        const size_t base = 80 + size_t(level) * 24;
        put64(base, 80 + size_t(levels) * 24);
        put64(base + 8, 1);
        put64(base + 16, 4);
    }
    return stream;
}

} // namespace

TEST_CASE("TranscodeKtx2BasisImage transcodes a real Basis-encoded KTX2 file to BC7 or RGBA8 fallback",
          "[texture-transcode]")
{
    auto bytes = ReadFileBytes(std::wstring(PREVIEW3D_TEST_ASSETS_DIR) + L"basisu_sample.ktx2");
    REQUIRE(bytes.has_value());

    auto result = import_worker::TranscodeKtx2BasisImage(*bytes);
    REQUIRE(result.has_value());
    CHECK(result->width == 8);
    CHECK(result->height == 8);
    CHECK((result->pixelFormat == model_core::PixelFormatId::BC7_UNORM
           || result->pixelFormat == model_core::PixelFormatId::RGBA8_UNORM));

    auto expectedBytes
        = model_core::ComputeImagePixelBytes(result->pixelFormat, result->width, result->height, 1);
    REQUIRE(expectedBytes.has_value());
    CHECK(result->pixelBytes.size() == *expectedBytes);
}

TEST_CASE("TranscodeKtx2BasisImage returns nullopt (never crashes/throws) on a corrupt/truncated buffer",
          "[texture-transcode]")
{
    std::vector<std::byte> garbage(64, std::byte{ 0x11 });
    auto result = import_worker::TranscodeKtx2BasisImage(garbage);
    CHECK_FALSE(result.has_value());
}

TEST_CASE("TranscodeKtx2BasisImage returns nullopt on an empty buffer", "[texture-transcode]")
{
    std::vector<std::byte> empty;
    auto result = import_worker::TranscodeKtx2BasisImage(empty);
    CHECK_FALSE(result.has_value());
}

TEST_CASE("TranscodeKtx2BasisImage rejects extreme declared dimensions before the KTX library",
          "[texture-transcode][security]")
{
    const uint64_t before = model_core::Ktx2DecoderInvocations().load();
    auto bytes = HostileKtx2Stream(/*width=*/100'000u, /*height=*/100'000u, /*levels=*/1);
    auto result = import_worker::TranscodeKtx2BasisImage(bytes);
    CHECK_FALSE(result.has_value());
    // The KTX library was never reached, so nothing expanded the declared size.
    CHECK(model_core::Ktx2DecoderInvocations().load() == before);
}

TEST_CASE("TranscodeKtx2BasisImage rejects an over-declared level count before the KTX library",
          "[texture-transcode][security]")
{
    const uint64_t before = model_core::Ktx2DecoderInvocations().load();
    auto bytes = HostileKtx2Stream(/*width=*/64u, /*height=*/64u, /*levels=*/64);
    auto result = import_worker::TranscodeKtx2BasisImage(bytes);
    CHECK_FALSE(result.has_value());
    CHECK(model_core::Ktx2DecoderInvocations().load() == before);
}
