// Stage 5 (KTX2/Basis texture transcode) unit tests -- exercise
// import_worker::TranscodeKtx2BasisImage directly against a real
// Basis-Universal-compressed KTX2 file (generated by
// interactive-viewer/tools/gen-test-glbs-ktx2.cpp via the real KTX-Software
// encode API). GltfImportTests.cpp's basisu_textured_triangle.glb/
// basisu_corrupt_ktx2.glb cases separately prove the real end-to-end
// worker path through GltfAdapter.cpp.

#include "TextureTranscodeAdapter.h"

#include "model_core/PixelFormats.h"

#include <catch2/catch_test_macros.hpp>
#include <platform/Win32Handle.h>

#include <windows.h>

#include <optional>
#include <vector>

#ifndef PREVIEW3D_TEST_ASSETS_DIR
#error "PREVIEW3D_TEST_ASSETS_DIR must be defined by Tests.ImportIsolation.vcxproj"
#endif

namespace {

std::optional<std::vector<std::byte>> ReadFileBytes(const std::wstring& path)
{
    platform::Win32Handle file(CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                                            OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr));
    if (!file) {
        return std::nullopt;
    }
    LARGE_INTEGER size{};
    if (!GetFileSizeEx(file.get(), &size) || size.QuadPart <= 0) {
        return std::nullopt;
    }
    std::vector<std::byte> bytes(static_cast<size_t>(size.QuadPart));
    DWORD bytesRead = 0;
    if (!ReadFile(file.get(), bytes.data(), static_cast<DWORD>(bytes.size()), &bytesRead, nullptr)
        || bytesRead != bytes.size()) {
        return std::nullopt;
    }
    return bytes;
}

} // namespace

TEST_CASE("TranscodeKtx2BasisImage transcodes a real Basis-encoded KTX2 file to BC7 or RGBA8 fallback",
          "[texture-transcode]")
{
    auto bytes = ReadFileBytes(std::wstring(PREVIEW3D_TEST_ASSETS_DIR) + L"basisu_sample.ktx2");
    REQUIRE(bytes.has_value());

    auto result = import_worker::TranscodeKtx2BasisImage(*bytes);
    REQUIRE(result.has_value());
    CHECK(result->width == 8);
    CHECK(result->height == 8);
    CHECK((result->pixelFormat == model_core::PixelFormatId::BC7_UNORM
           || result->pixelFormat == model_core::PixelFormatId::RGBA8_UNORM));

    auto expectedBytes
        = model_core::ComputeImagePixelBytes(result->pixelFormat, result->width, result->height, 1);
    REQUIRE(expectedBytes.has_value());
    CHECK(result->pixelBytes.size() == *expectedBytes);
}

TEST_CASE("TranscodeKtx2BasisImage returns nullopt (never crashes/throws) on a corrupt/truncated buffer",
          "[texture-transcode]")
{
    std::vector<std::byte> garbage(64, std::byte{ 0x11 });
    auto result = import_worker::TranscodeKtx2BasisImage(garbage);
    CHECK_FALSE(result.has_value());
}

TEST_CASE("TranscodeKtx2BasisImage returns nullopt on an empty buffer", "[texture-transcode]")
{
    std::vector<std::byte> empty;
    auto result = import_worker::TranscodeKtx2BasisImage(empty);
    CHECK_FALSE(result.has_value());
}
