// SPIKE-8a (T02) regression coverage for the prototype CPU tile rasterizer.
//
// The golden images are committed under thumbnail-spike/goldens and are
// regenerated by RasterizerSpike.exe (`goldens` mode). Comparison is the
// tolerant perceptual metric in docs/design/testing-strategy.md, not byte
// equality, so a Debug/Release floating-point difference does not fail the
// suite while a real rendering regression does.

#include "PamImage.h"
#include "SceneFixtures.h"
#include "ThumbnailRasterizer.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <string>
#include <vector>

#include <draco/compression/decode.h>
#include <draco/compression/encode.h>
#include <draco/mesh/mesh.h>
#include <draco/mesh/triangle_soup_mesh_builder.h>

namespace
{

using thumbnail_rasterizer::GeometryView;
using thumbnail_rasterizer::Image;
using thumbnail_rasterizer::LinearRgb;
using thumbnail_rasterizer::Options;
using thumbnail_rasterizer::Point;
using thumbnail_rasterizer::Render;
using thumbnail_rasterizer::Status;
using thumbnail_rasterizer::Triangle;
using thumbnail_rasterizer::Vec3;

constexpr std::uint8_t kHasNormals = thumbnail_rasterizer::kTriangleHasNormals;
constexpr std::uint8_t kMasked = thumbnail_rasterizer::kTriangleMasked;
constexpr std::uint8_t kDoubleSided = thumbnail_rasterizer::kTriangleDoubleSided;

std::string GoldenPath(const char* name)
{
    return (std::filesystem::path(THUMBNAIL_SPIKE_GOLDEN_DIR) / name).string();
}

struct DiffStats
{
    double meanAbs = 0.0;
    int maxAbs = 0;
};

DiffStats Compare(const std::vector<std::uint8_t>& bgra, int width, int height,
                  const std::vector<std::uint8_t>& goldenRgba)
{
    DiffStats stats;
    const std::size_t pixels = static_cast<std::size_t>(width) * height;
    REQUIRE(bgra.size() == pixels * 4);
    REQUIRE(goldenRgba.size() == pixels * 4);
    std::uint64_t total = 0;
    for (std::size_t i = 0; i < pixels; ++i) {
        const std::uint8_t rendered[4] = { bgra[i * 4 + 2], bgra[i * 4 + 1], bgra[i * 4 + 0],
                                           bgra[i * 4 + 3] };
        for (int c = 0; c < 4; ++c) {
            const int diff = std::abs(static_cast<int>(rendered[c]) - static_cast<int>(goldenRgba[i * 4 + c]));
            total += static_cast<std::uint64_t>(diff);
            stats.maxAbs = (std::max)(stats.maxAbs, diff);
        }
    }
    stats.meanAbs = static_cast<double>(total) / static_cast<double>(pixels * 4);
    return stats;
}

Triangle MakeTriangle(const Vec3& a, const Vec3& b, const Vec3& c, const LinearRgb& color,
                      std::uint8_t flags)
{
    Triangle triangle{};
    triangle.p[0] = a;
    triangle.p[1] = b;
    triangle.p[2] = c;
    triangle.color[0] = triangle.color[1] = triangle.color[2] = color;
    triangle.alpha = 1.0f;
    triangle.flags = flags;
    return triangle;
}

} // namespace

TEST_CASE("Rasterizer output is deterministic and premultiplied", "[thumbnail-rasterizer]")
{
    auto mesh = thumbnail_spike::MakeGoldenMesh();
    GeometryView geometry;
    geometry.triangles = mesh.triangles;

    Options options;
    options.size = 128;
    options.supersample = 2;

    Image first;
    Image second;
    REQUIRE(Render(geometry, options, first) == Status::Ok);
    REQUIRE(Render(geometry, options, second) == Status::Ok);
    CHECK(first.bgraPremultiplied == second.bgraPremultiplied);
    for (std::size_t i = 0; i < first.bgraPremultiplied.size(); i += 4) {
        const int alpha = first.bgraPremultiplied[i + 3];
        CHECK(first.bgraPremultiplied[i + 0] <= alpha);
        CHECK(first.bgraPremultiplied[i + 1] <= alpha);
        CHECK(first.bgraPremultiplied[i + 2] <= alpha);
    }
}

TEST_CASE("Golden mesh images match at 32/64/256/512 px", "[thumbnail-rasterizer][golden]")
{
    auto mesh = thumbnail_spike::MakeGoldenMesh();
    GeometryView geometry;
    geometry.triangles = mesh.triangles;

    for (int size : { 32, 64, 256, 512 }) {
        Options options;
        options.size = size;
        options.supersample = 2;
        Image image;
        REQUIRE(Render(geometry, options, image) == Status::Ok);

        int goldenWidth = 0;
        int goldenHeight = 0;
        std::vector<std::uint8_t> golden;
        REQUIRE(thumbnail_rasterizer::LoadPamRgba(
            GoldenPath((std::string("mesh-") + std::to_string(size) + ".pam").c_str()).c_str(),
            goldenWidth, goldenHeight, golden));
        CHECK(goldenWidth == size);
        CHECK(goldenHeight == size);
        const DiffStats stats = Compare(image.bgraPremultiplied, size, size, golden);
        INFO("mesh size " << size << " meanAbs=" << stats.meanAbs << " maxAbs=" << stats.maxAbs);
        CHECK(stats.meanAbs <= 2.0);
        CHECK(stats.maxAbs <= 48);
    }
}

TEST_CASE("Golden point-cloud images match at 32/64/256/512 px", "[thumbnail-rasterizer][golden]")
{
    auto cloud = thumbnail_spike::MakeGoldenPointCloud();
    GeometryView geometry;
    geometry.points = cloud.points;

    for (int size : { 32, 64, 256, 512 }) {
        Options options;
        options.size = size;
        options.supersample = 2;
        Image image;
        REQUIRE(Render(geometry, options, image) == Status::Ok);

        int goldenWidth = 0;
        int goldenHeight = 0;
        std::vector<std::uint8_t> golden;
        REQUIRE(thumbnail_rasterizer::LoadPamRgba(
            GoldenPath((std::string("points-") + std::to_string(size) + ".pam").c_str()).c_str(),
            goldenWidth, goldenHeight, golden));
        const DiffStats stats = Compare(image.bgraPremultiplied, size, size, golden);
        INFO("points size " << size << " meanAbs=" << stats.meanAbs << " maxAbs=" << stats.maxAbs);
        CHECK(stats.meanAbs <= 2.0);
        CHECK(stats.maxAbs <= 48);
    }
}

TEST_CASE("Empty geometry reports NoGeometry and invalid options are rejected",
          "[thumbnail-rasterizer]")
{
    GeometryView empty;
    Options options;
    options.size = 64;
    Image image;
    CHECK(Render(empty, options, image) == Status::NoGeometry);

    auto mesh = thumbnail_spike::MakeGoldenMesh();
    GeometryView geometry;
    geometry.triangles = mesh.triangles;
    Options invalid;
    invalid.size = 0;
    CHECK(Render(geometry, invalid, image) == Status::InvalidOptions);
    invalid.size = 64;
    invalid.supersample = 0;
    CHECK(Render(geometry, invalid, image) == Status::InvalidOptions);
}

TEST_CASE("Masked triangle below cutoff is discarded", "[thumbnail-rasterizer]")
{
    Triangle triangle = MakeTriangle({ 0, 0, 0 }, { 1, 0, 0 }, { 0, 1, 0 }, { 0.8f, 0.2f, 0.1f },
                                     kMasked | kDoubleSided);
    triangle.alpha = 0.2f;
    triangle.maskCutoff = 0.5f;
    GeometryView geometry;
    geometry.triangles = std::span<const Triangle>(&triangle, 1);

    Options options;
    options.size = 64;
    options.supersample = 1;
    options.floorShadow = false;
    Image image;
    REQUIRE(Render(geometry, options, image) == Status::Ok);
    for (std::uint8_t value : image.bgraPremultiplied) CHECK(value == 0);

    triangle.alpha = 0.9f;
    REQUIRE(Render(geometry, options, image) == Status::Ok);
    const bool anyOpaque = std::any_of(image.bgraPremultiplied.begin(), image.bgraPremultiplied.end(),
                                       [](std::uint8_t v) { return v != 0; });
    CHECK(anyOpaque);
}

TEST_CASE("Transparent material uses a weighted-opaque approximation", "[thumbnail-rasterizer]")
{
    Triangle opaque = MakeTriangle({ 0, 0, 0 }, { 1, 0, 0 }, { 0, 1, 0 }, { 0.8f, 0.2f, 0.1f },
                                   kDoubleSided);
    Triangle transparent = opaque;
    transparent.alpha = 0.4f;

    Options options;
    options.size = 64;
    options.supersample = 1;
    options.floorShadow = false;

    GeometryView opaqueView;
    opaqueView.triangles = std::span<const Triangle>(&opaque, 1);
    GeometryView transparentView;
    transparentView.triangles = std::span<const Triangle>(&transparent, 1);

    Image opaqueImage;
    Image transparentImage;
    REQUIRE(Render(opaqueView, options, opaqueImage) == Status::Ok);
    REQUIRE(Render(transparentView, options, transparentImage) == Status::Ok);
    CHECK(opaqueImage.bgraPremultiplied != transparentImage.bgraPremultiplied);
    // Weighted-opaque keeps a depth-writing, opaque result rather than dropping alpha.
    CHECK(std::any_of(transparentImage.bgraPremultiplied.begin(),
                      transparentImage.bgraPremultiplied.end(),
                      [](std::uint8_t v) { return v == 255; }));
}

TEST_CASE("Depth test keeps the nearer triangle", "[thumbnail-rasterizer]")
{
    // Two triangles that project to the same screen polygon but sit at
    // different view depths: offsetting along the fixed view forward direction
    // leaves the orthographic projection unchanged while moving view z. The
    // near one is red; the far green one would win if the depth test failed.
    const Vec3 forward{ -0.5773502691896258, -0.5773502691896258, -0.5773502691896258 };
    auto offset = [&](const Vec3& p, double d) {
        return Vec3{ p.x + forward.x * d, p.y + forward.y * d, p.z + forward.z * d };
    };
    const Vec3 base0{ 0, 0, 0 };
    const Vec3 base1{ 1, 0, 0 };
    const Vec3 base2{ 0, 1, 0 };
    Triangle nearTriangle =
        MakeTriangle(offset(base0, -0.5), offset(base1, -0.5), offset(base2, -0.5),
                     { 0.9f, 0.05f, 0.05f }, kDoubleSided);
    Triangle farTriangle =
        MakeTriangle(offset(base0, 0.5), offset(base1, 0.5), offset(base2, 0.5),
                     { 0.05f, 0.9f, 0.05f }, kDoubleSided);
    Triangle triangles[2] = { farTriangle, nearTriangle };
    GeometryView geometry;
    geometry.triangles = triangles;

    Options options;
    options.size = 64;
    options.supersample = 1;
    options.floorShadow = false;
    Image image;
    REQUIRE(Render(geometry, options, image) == Status::Ok);

    // Find the maximum-coverage pixel and assert it is red-dominant (BGRA order).
    std::size_t best = 0;
    int bestAlpha = -1;
    for (std::size_t i = 0; i < image.bgraPremultiplied.size(); i += 4) {
        if (image.bgraPremultiplied[i + 3] > bestAlpha) {
            bestAlpha = image.bgraPremultiplied[i + 3];
            best = i;
        }
    }
    CHECK(image.bgraPremultiplied[best + 2] > image.bgraPremultiplied[best + 1]);
}

TEST_CASE("Cap sampler is deterministic, bounded and seed-sensitive", "[thumbnail-rasterizer]")
{
    const std::uint64_t seed = thumbnail_spike::SeedFromString("spike8-mesh");
    auto first = thumbnail_spike::GenerateLargeMesh(200000, 4096, seed);
    auto second = thumbnail_spike::GenerateLargeMesh(200000, 4096, seed);
    CHECK(first.inspected == 200000);
    CHECK(first.triangles.size() == 4096);
    REQUIRE(first.triangles.size() == second.triangles.size());
    CHECK(first.triangles[0].p[0].x == second.triangles[0].p[0].x);
    CHECK(first.triangles[4095].p[2].z == second.triangles[4095].p[2].z);

    auto other = thumbnail_spike::GenerateLargeMesh(200000, 4096, seed ^ 0x1234);
    CHECK(other.triangles.size() == 4096);
    CHECK(first.triangles[0].p[0].x != other.triangles[0].p[0].x);

    auto cloud = thumbnail_spike::GenerateLargePointCloud(100000, 2048, seed);
    CHECK(cloud.inspected == 100000);
    CHECK(cloud.points.size() == 2048);
}

// Exercises the bounded Draco decoder that ADR-0003 enables in the provider,
// then feeds the decoded geometry through the rasterizer. This is the decoder
// dependency closure the spike actually runs; T03 measures the real compressed
// GLB fixtures (interactive-viewer/test-assets/draco_*.glb) end to end inside
// the Shell surrogate.
TEST_CASE("Draco-decoded geometry rasterizes", "[thumbnail-rasterizer][draco]")
{
    draco::TriangleSoupMeshBuilder builder;
    builder.Start(1);
    const int positionId = builder.AddAttribute(draco::GeometryAttribute::POSITION, 3, draco::DT_FLOAT32);
    builder.SetAttributeUniqueId(positionId, 0);
    float p0[3] = { 0.0f, 0.0f, 0.0f };
    float p1[3] = { 1.0f, 0.0f, 0.0f };
    float p2[3] = { 0.0f, 1.0f, 0.0f };
    builder.SetAttributeValuesForFace(positionId, draco::FaceIndex(0), p0, p1, p2);
    auto mesh = builder.Finalize();
    REQUIRE(mesh != nullptr);

    draco::Encoder encoder;
    encoder.SetAttributeQuantization(draco::GeometryAttribute::POSITION, 26);
    draco::EncoderBuffer encoded;
    REQUIRE(encoder.EncodeMeshToBuffer(*mesh, &encoded).ok());

    draco::DecoderBuffer buffer;
    buffer.Init(encoded.data(), encoded.size());
    auto decoded = draco::Decoder().DecodeMeshFromBuffer(&buffer);
    REQUIRE(decoded.ok());
    const std::unique_ptr<draco::Mesh>& decodedMesh = decoded.value();
    REQUIRE(decodedMesh != nullptr);
    REQUIRE(decodedMesh->num_faces() == 1);

    const draco::PointAttribute* attribute = decodedMesh->GetAttributeByUniqueId(0);
    if (!attribute) attribute = decodedMesh->attribute(0);
    REQUIRE(attribute != nullptr);
    REQUIRE(attribute->num_components() == 3);

    std::array<Vec3, 3> positions{};
    for (std::uint32_t i = 0; i < decodedMesh->num_points() && i < 3; ++i) {
        const draco::PointIndex pointIndex(i);
        std::array<float, 3> value{};
        REQUIRE(attribute->GetValue<float, 3>(attribute->mapped_index(pointIndex), &value));
        positions[i] = { value[0], value[1], value[2] };
    }

    Triangle triangle = MakeTriangle(positions[0], positions[1], positions[2],
                                     { 0.6f, 0.3f, 0.1f }, kDoubleSided);
    GeometryView geometry;
    geometry.triangles = std::span<const Triangle>(&triangle, 1);
    Options options;
    options.size = 32;
    options.supersample = 1;
    options.floorShadow = false;
    Image image;
    CHECK(Render(geometry, options, image) == Status::Ok);
    CHECK(std::any_of(image.bgraPremultiplied.begin(), image.bgraPremultiplied.end(),
                      [](std::uint8_t v) { return v != 0; }));
}